//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantKuUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailorder
    {
        public int detailid { get; set; }
        public int orderid { get; set; }
        public int menuid { get; set; }
        public int qty { get; set; }
        public int total { get; set; }
        public string status { get; set; }
    
        public virtual headorder headorder { get; set; }
        public virtual msmenu msmenu { get; set; }
    }
}
