//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantKuUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class headorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public headorder()
        {
            this.detailorders = new HashSet<detailorder>();
        }
    
        public int orderid { get; set; }
        public string employeeid { get; set; }
        public int memberid { get; set; }
        public System.DateTime date { get; set; }
        public string payment { get; set; }
        public string bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailorder> detailorders { get; set; }
        public virtual msemployee msemployee { get; set; }
        public virtual msmember msmember { get; set; }
    }
}
