//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantKuUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class msmenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msmenu()
        {
            this.detailorders = new HashSet<detailorder>();
        }
    
        public int menuid { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public byte[] photo { get; set; }
        public string path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailorder> detailorders { get; set; }
    }
}
